// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apache/rocketmq/v2/definition.proto

package apache.rocketmq.v2;

/**
 * Protobuf enum {@code apache.rocketmq.v2.PeekDirection}
 */
public enum PeekDirection
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>FORWARD = 0;</code>
   */
  FORWARD(0),
  /**
   * <code>BACKWARD = 1;</code>
   */
  BACKWARD(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>FORWARD = 0;</code>
   */
  public static final int FORWARD_VALUE = 0;
  /**
   * <code>BACKWARD = 1;</code>
   */
  public static final int BACKWARD_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static PeekDirection valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static PeekDirection forNumber(int value) {
    switch (value) {
      case 0: return FORWARD;
      case 1: return BACKWARD;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<PeekDirection>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      PeekDirection> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<PeekDirection>() {
          public PeekDirection findValueByNumber(int number) {
            return PeekDirection.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return apache.rocketmq.v2.MQDomain.getDescriptor().getEnumTypes().get(13);
  }

  private static final PeekDirection[] VALUES = values();

  public static PeekDirection valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private PeekDirection(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:apache.rocketmq.v2.PeekDirection)
}

